### ISSUE TITLE
Fix Poussetaches Kubernetes Network issues

### ISSUE THREAD

**Issue by howaboutudance** [howaboutudance/microblog.pub#6]
Deploying into to Kuberenetes works well but Poussetaches seems to not handle being connected to a K8 service object with a clusterIP dns alias, need to be static IP.

**Comment by 1804devs** [comment]
https://stackoverflow.com/questions/58311862/connecting-to-mongodb-in-kubernetes-pod-with-kubernetes-client-using-python


i had trouble looking up "Poussetaches" online ..

**Comment by howaboutudance** [comment]
sorry typo, microblog.pub is using a custom task executor named [Poussetaches](https://github.com/tsileo/poussetaches)

**Comment by howaboutudance** [comment]
I think I was able to fix all this from the most recent push I made to the issue5 branch
